config/routes.rb
Rails.application.routes.draw do
  resources :widgets
  resources :votes
  resources :stars
  root 'topics#index'

  resources :topics do
    resources :votes, controller: 'votes'

     member do
       post 'vote'
      end

  		scope "(:locale)", locale: /en|es|de/ do

      end
  end


  get '/votes/new' => 'vote#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :votes, dependent: :destroy
  validates_presence_of :title, :message => "This field cant be blank"
  validates_presence_of :description, :message => "This field cant be blank"

  def number_of_votes
    sum = 0
    votes.each{|v| sum = sum + v.stars}
    sum
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :topic
  validates_presence_of :stars, :message => "This field cant be blank"

  def new
    @vote = Vote.new
  end
end

app/models/widget.rb
class Widget < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale
 
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end


 

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
    @votes = Vote.all

  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end



  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :description, :votes)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController


  def index

    @votes = Vote.all
  end


  def show
    @votes = topic.votes(params[:id])
  end

  def new
    @votes = Vote.new
  end
  def create
     topic_id = params["topic_id"]

    @votes =Vote.new(stars: params["stars"],topic: Topic.find(params["vote"]["topic_id"]))
    if @votes.save

     flash[:succes] = 'Your vote was succesfully submitted'
     redirect_to topics_path
    else
      render "new"
    end
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Suggestotron</title>
    <%= csrf_meta_tags %>
<div> <%= t('Language') %>

<%=link_to 'Deutsch', url_for( :locale => 'de' )%>
<%=link_to "Spanish", url_for( :locale => 'es')%>
<%=link_to "English", url_for( :locale => 'en')%>
</div>

<%= yield %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body class="image">
  <% flash.each do |key, value| %>
  <p> <%= value %> </p>
  <% end %>

  </body>
</html>

app/views/topics/_form.html.erb
<%= form_for(topic) do |f| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t('title') %>
    <%= f.text_field :title %>

  </div>



  <div class="field">
    <%= f.label t('description') %>
    <%= f.text_area :description %>
  </div>



  <div class="actions">
    <%= f.submit t('create topic')%>
  </div>

<% end %>

app/views/topics/edit.html.erb
<h1> <%=t('Editing Topic') %> </h1>

<%= render 'form', topic: @topic, votes: @vote %>

<%= link_to t('Show'), @topic %> |
<%= link_to t('Back'), topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>
<div class="blue_text"><h1 > <%= t('Topics')%> </h1> </div>
 <div class="container">

  <div class="columns">
    <div class="one-fourth column" >
      <span class="border text-center d-block p-2 white_text">
        <%=t('title') %>
      </span>
    </div>
    <div class="one-fourth column" >
     <span class="border text-center d-block p-2 white_text" > <%=  t('description')%>

     </div>
    <div class="one-fourth column" >
    <span class="border text-center d-block p-2 white_text">
    <%= t('Stars') %>
    </div>
    <div class="one-fourth column"></div>
  </div>
  </div>
  <% @topics.each do |topic| %>
    <div class="width_letters">
      <div class="columns">
        <div  class="one-fifth column white_text" ><%= topic.title %></div>
        <div class="one-fifth column white_text" >  <%= topic.description %></div>
        <div class="one-fifth column white_text"><%= topic.number_of_votes%></div>
        <div class="two-fifth column"></div>
      </div>
      <div class="btn-group">
        <%= link_to t('Show'), topic_path(topic), class: "btn btn-sm" %>
        <%= link_to t('Edit'), edit_topic_path(topic), class: "btn btn-sm" %>
        <%= link_to t('Destroy'), topic, class: "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to t('vote'),   new_topic_vote_path(topic) , class: "btn btn-sm btn-primary"%>
      </div>
      <div class="image"></div>​
    </div>
  <% end %>
  <div class="background">
  </div>
</div>

<br>
 <%= link_to t('New Topic'), new_topic_path%>

 </div>

app/views/topics/new.html.erb
<h1> <%= t('New Topic') %></h1>
<%= render 'form', topic: @topic %>
<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @topic.description %>
<p>
	<strong> Stars: </strong>
	<%= @topic.votes.count %>
</p>
</p>

<%= link_to t('Edit'), edit_topic_path(@topic) %> |
<%= link_to t('Back'), topics_path %>

app/views/vote/new.html.erb
<h1> <%=t('New Vote')%></h1> 
<%= form_for (@vote) do |f| %> 

  <div class="field"> 

  <%= number_field_tag :votes, nil, min: 0, max: 5%> 

  </div> 

     <div class="actions"> 

      <% f.submit"create vote" %> 

      </div> 

<% end %> 

<%= link_to t('Back'), topics_path %>

app/views/votes/index.html.erb
<header> No funciona </header>

app/views/votes/new.html.erb
<h1> <%=t('New Vote')%></h1>

<%= form_for @votes do |f| %>

  <div class="form-group">
  <%= f.label :votes %>
  <%= number_field_tag :stars, nil, min: 0, max: 5 class: "form-control input-block"%>
  <%= f.hidden_field :topic_id, :value => params[:topic_id] %>
  </div>



 <p>
 	 <%= f.submit "submit"%>
 </p>


<%= link_to t('Back'), topics_path(params[:topic_id]) %>

 <% end %>

app/views/votes/show.html.erb
<h1>Vote succesfully submited</h1>


<%= link_to t('Home_page'), topics_path %>